//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        public autor()
        {
            this.autorKnjige = new HashSet<autorKnjige>();
        }
    
        public int idAutora { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
    
        public virtual ICollection<autorKnjige> autorKnjige { get; set; }
    }
}
