//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class clanarina
    {
        public clanarina()
        {
            this.racun = new HashSet<racun>();
        }
    
        public int idClanarina { get; set; }
        public int cijena { get; set; }
        public System.DateTime datumPlacanja { get; set; }
        public System.DateTime datumIsteka { get; set; }
        public int korisnik { get; set; }
    
        public virtual korisnik korisnik1 { get; set; }
        public virtual ICollection<racun> racun { get; set; }
    }
}
