//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class izdavac
    {
        public izdavac()
        {
            this.knjiga = new HashSet<knjiga>();
        }
    
        public int idIzdavaca { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string kontakt { get; set; }
    
        public virtual ICollection<knjiga> knjiga { get; set; }
    }
}
