//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class lokacijaKnjige
    {
        public lokacijaKnjige()
        {
            this.knjiga = new HashSet<knjiga>();
        }
    
        public int idLokacije { get; set; }
        public int kat { get; set; }
        public string odjeljak { get; set; }
        public string stalaza { get; set; }
        public string polica { get; set; }
    
        public virtual ICollection<knjiga> knjiga { get; set; }
    }
}
