//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class posudivanje
    {
        public int idPosudbe { get; set; }
        public int korisnik { get; set; }
        public int knjiga { get; set; }
        public Nullable<System.DateTime> datumPosudbe { get; set; }
        public Nullable<System.DateTime> datumVracanja { get; set; }
    
        public virtual knjiga knjiga1 { get; set; }
        public virtual korisnik korisnik1 { get; set; }
    }
}
