//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class autorKnjige
    {
        public int id_zapisa { get; set; }
        public int knjiga { get; set; }
        public int autor { get; set; }
    
        public virtual autor autor1 { get; set; }
        public virtual knjiga knjiga1 { get; set; }
    }
}
