//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public korisnik()
        {
            this.clanarina = new HashSet<clanarina>();
            this.posudba = new HashSet<posudivanje>();
        }
    
        public int idKorisnika { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
        public string oib { get; set; }
        public string email { get; set; }
        public string brojTelefona { get; set; }
        public int tipKorisnika { get; set; }
    
        public virtual ICollection<clanarina> clanarina { get; set; }
        public virtual ICollection<posudivanje> posudba { get; set; }
        public virtual tipKorisnika tipKorisnika1 { get; set; }
    }
}
