//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjižnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class knjiga
    {
        public knjiga()
        {
            this.autorKnjige = new HashSet<autorKnjige>();
            this.posudba = new HashSet<posudivanje>();
        }
    
        public int idKnjiga { get; set; }
        public string naziv { get; set; }
        public string godinaIzdavanja { get; set; }
        public int izdavac { get; set; }
        public int zanr { get; set; }
        public int lokacijaKnjige { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> trenutnaKolicina { get; set; }
    
        public virtual ICollection<autorKnjige> autorKnjige { get; set; }
        public virtual izdavac izdavac1 { get; set; }
        public virtual zanr zanr1 { get; set; }
        public virtual lokacijaKnjige lokacijaKnjige1 { get; set; }
        public virtual ICollection<posudivanje> posudba { get; set; }
    }
}
